domain: cophee-lab.com       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://cophee.github.io  # the base hostname and protocol for your site, e.g. http://example.com

remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme 
  - jekyll-scholar
  - jekyll-toc

defaults:
  - scope:
      path: ""
    values:
      layout: "base"


# # Content configuration
# ## Basic Information
name: COPHEE @ NYU
description: COPHEE lab's website
fullform: COmputing for Performance, Health, and Empathetic Experiences
affiliation: Tandon School of Engineering at New York University
email: v.das.swain@nyu.edu

# ## Social Media
# google_scholar: https://scholar.google.com/citations?user=x7mC-94AAAAJ&hl=en
# cv_link: assets/files/vedantswain_resume.pdf
# linkedin: https://www.linkedin.com/in/vedant-das-swain/
# twitter: https://twitter.com/VedantNeedMoEdu
# bluesky: https://bsky.app/profile/vedantneedmoedu.bsky.social

# ## Images (e.g., your profile picture and your website's favicon) 
avatar: assets/images/avatar.png
favicon: assets/images/favicon.ico

# ## Tracking
# googletag_id: G-ZFVZQV5NHX

# ## TOC
toc:
  min_level: 2
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-